AWSTemplateFormatVersion: 2010-09-09
Description: >-
  dynamodb-lambda

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  PutItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put-item.putItemHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MusicTable
      Environment:
        Variables:
          TABLE_NAME: !Ref MusicTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST

  MusicTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Music"
      AttributeDefinitions:
        - AttributeName: "Artist"
          AttributeType: "S"
        - AttributeName: "SongTitle"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Artist"
          KeyType: "HASH"
        - AttributeName: "SongTitle"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
