AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda

  Sample SAM Template for lambda

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      AutoPublishAlias: "live"
      DeploymentPreference:
        Type: Canary10Percent5Minutes
        Enabled: true
        PassthroughCondition: true
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  SourceTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: SourceTopic

  ConsumeSourceTopicFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: consume-source-topic/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt OnSuccessQueue.QueueName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt OnFailureQueue.QueueName
      Events:
        TopicEvent:
          Type: SNS
          Properties:
            Topic: !Ref SourceTopic
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 60
        MaximumRetryAttempts: 2
        DestinationConfig:
          OnSuccess:
            Type: SQS
            Destination: !GetAtt OnSuccessQueue.Arn
          OnFailure:
            Type: SQS
            Destination: !GetAtt OnFailureQueue.Arn

  OnSuccessQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: OnSuccessQueue

  OnFailureQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: OnFailureQueue
